#!/usr/bin/env python3
"""
Manual cluster name mappings for Mycelica
Generated by Claude based on keyword analysis
"""

import sqlite3
import json
from datetime import datetime

# Manual cluster name mappings based on keyword analysis
CLUSTER_NAMES = {
    0: "Linux Packaging",  # pkgbuild, package, build, fyne, binary, install
    1: "Windows System Issues",  # windows, boot, manjaro, autohotkey, systemroot
    2: "Probability & Statistics",  # 50, like, coin, probability, model, face, flip
    3: "Web Development",  # window, created, preview, web, mobile, feature, analysis
    4: "Job Applications",  # technical, support, role, servicenow, work, foxway, repair
    5: "UX Design Work",  # tartu, ux, app, product, work, qa, user, roles, experience
    6: "3D Printing Setup",  # janus, mkspi, crowsnest, gateway, printer components
    7: "Local AI & LLMs",  # local, https, github, llm, open source, ollama
    8: "GUI Development",  # fyne, key, widget, func, code, hotkey, keys, settings
    9: "Mental Health Treatment",  # treatment, options, resistant depression, ketamine
    10: "Space & Physics",  # feel, symptoms, moon, gravity, body, earth, create
    11: "AI Philosophy",  # just, like, think, people, ai, feel, want, right, know
    12: "Digital Signatures",  # digital, eu, eidas, signature, google, pdf, signed
    13: "Home DIY Projects",  # water, just, hot, dry, use, wood, air, bath, primer
    14: "Home Automation",  # home, home assistant, assistant, template, cat, success
    15: "Device Compatibility",  # current, supported, device, block, estonia
    16: "Browser Customization",  # echo, firefox, chrome, folder, profile, css
    17: "App Development Feedback",  # nurse, doing, v1, want, app, features, perfect
    18: "3D Printer Configuration",  # klipper, printer, mks, mcu, config, file, mkspi
    19: "Code Highlighting",  # code, files, highlight, syntax, js, css, browser
    20: "Display & Graphics",  # nvidia, hdmi, bash, sudo, output, monitor, kde
    21: "Network Configuration",  # 168, 192, enable, ack, router, tcp
    22: "AutoHotkey Scripts",  # add, monitormenu, text, feature, autohotkey, value
    23: "Phone Firmware",  # usb, device, edl, oneplus, nord, mode, tool, phone
    24: "Hardware Drivers",  # src, button, hidpp20, driver, libratbag, mapping
    25: "Email Security",  # email, com, use, send, fake, channel, startup, scam
    26: "Game Development",  # years, unity, 10 years, built, terrain, tartubus
    27: "Research Systems",  # research, board, like, systems, using, build, eeg
    28: "Political Analysis",  # trump, state, data, administration, fascist, article
    29: "Networking Hardware",  # cable, like, drones, fiber, rf, optic
    30: "Android Development",  # adb, android, linux, device, watch, tools, app
    31: "Database Design",  # enemy, table, concat, type, fields, field, template
    32: "Medication Discussion",  # yeah, quetiapine, option, fruit, honestly, way
    33: "Office Automation",  # excel, teams, items, apply_to_each, message, action
    34: "Programming Functions",  # int, dacwrite, value, void, return, func, delay
    35: "Text & Unicode",  # text, like, characters, unicode, qr, combining, letter
    36: "Electronics Projects",  # pin, esp32, l293dne, speaker, audio, ground, power
    37: "Historical Politics",  # nato, warsaw pact, formal, countries, membership
    38: "Software Licensing",  # dating, app, license, use, code, repository, commercial
    39: "Data Management",  # files, csv, sqlite, csvs, onedrive, folders, database
    40: "System Monitoring",  # software, process, adsknlm, tracking, getkeystate
    41: "PCB Design",  # pitch, smd, openbci, fine, components, 0603, packages
    42: "Conversation Analysis",  # conversation, context, mycelica, conversations, api
    43: "API Development",  # api, data, request, status, post, sql, partners, telemetry
    44: "Military Technology",  # 100, drones, second, packets, 500, military, budget
    45: "Backend Services",  # firebase, app, backend, database, authentication, console
    46: "Database Administration",  # sudo, mnt, mount, dev, bash, mariadb, mysql
    47: "Creative Writing",  # different, names, season, hummus, story, bookshop, arabic
    48: "Museum Work",  # work, job, museum, artifacts, cultural, preservation, estonian
    49: "Project Planning",  # md, project, instructions, files, bus, phase, api
    50: "Software Testing",  # release, testing, version, create, app, github, build
    51: "Job Search",  # position, application, good, genuinely, role, randomness
    52: "File Conversion",  # file, stl, import, openscad, notes, conversations, export
    53: "Mobile App Development",  # android, expo, app, gradle, build, sdk, flutter, react
    54: "Character Description",  # dark, thoughtful, natural, appearance, length
    55: "Health Issues",  # bad, right, like, breath, bad breath, reflux, acid, ram
    56: "Audio Processing",  # audio, effects, voice, mp3, like, want, app, files, sox
    57: "Web Browsers",  # edge, app, chrome, windows, electron, apps, chromium
    58: "Database Setup",  # user, mariadb, root, create, database, localhost, password
    59: "Development Tools",  # build, windhawk, source, code, src, files, vscode
    60: "Exercise & Wellness",  # pilates, just, body, like, need, pop, want, jesus
    61: "Version Control",  # ll, gitignore, directory, yourspecificdir, folders
    62: "Game Design",  # 3d, style, like, time, game, smooth, convergence, 2d
    63: "Personal Stories",  # gerald, margaret, paul, salt, shaker, nurse, years
    64: "Audio Devices",  # pro, buds, oneplus, enco, oppo, sudio, anc, nord buds
    65: "Estonian Language",  # программер, добавлен, 2025, добавлены, программеры
    66: "Database Errors",  # error, connection, info, mysql, message, test, protocol
    67: "Language Learning",  # estonian, english, language, case, book, natural, watch
    68: "Vision & Perception",  # vision, brain, eye, visual, external, eyes, convergence
    69: "Heating Systems",  # heat, just, coals, air, chimney, close, intake, heating
    70: "Medication Effects",  # weight, fruit, quetiapine, eating, metabolic, lose
    71: "Input Methods",  # keyboard, scanner, layout, characters, running, application
    72: "HVAC Systems",  # door, furnace, closed, airflow, air, fine, minutes, burn
    73: "Programming Languages",  # rust, performance, applications, systems, language
    74: "Personal Reflection",  # say, going, know, wrote, long, honestly, appointment
    75: "Software Development",  # status, approach, professional, test, debugging, scrum
    76: "Neuroscience",  # evidence, learning, neuroplasticity, sleep, bdnf, plasticity
    77: "Data Structures",  # values, object, nok, let, column, tabledata, objectkeys
    78: "Android Flashing",  # fastboot, img, recovery, flash, boot, partition, bash
    79: "Biology & DNA",  # track, double, single, base, pairs, phase, dna
    80: "Network Security",  # suspicious, countries, connections, connecting, services
    81: "Game Projects",  # kalevipoeg, hell, voxel, estonian, hedgehog, source, game
    82: "Network Troubleshooting",  # driver, wifi, power, device, ping, powershell
    83: "E-commerce Platforms",  # temu, quality, wish, shipping, products, better
    84: "Language Expertise",  # things, words, person, specialist, estonian words
    85: "Graphics Programming",  # skybox, sky, debug, log, column, rendersettings
    86: "Python Libraries",  # pypropack, propack, build, pyf, lib, double
    87: "Transportation Systems",  # ja, masinat, kui, et, masina, süsteem, cultural
    88: "Work Sessions",  # session, break, min, work, 90, widget, settings
    89: "UI Interactions",  # click, react, monke, add reaction, november 2025
    90: "Database Schema",  # user_id, key, text, null, table, users, datetime
    91: "Browser Extensions",  # gamut, ublock, origin, block, element, click, browser
    92: "Operating Systems",  # kernel, linux, sites, specific, archives, repositories
    93: "Version Control",  # git, lfs, master, github, push, origin, bash, remote
    94: "System Login",  # login, sddm, bluetooth, bash, sudo, phone, service
    95: "Political Systems",  # political, donors, administration, party, advisors
    96: "Container Technology",  # docker, home, home assistant, homeassistant, run
    97: "Device Programming",  # self, device, resync, args, error, signal, print
    98: "Mental Health",  # dissociation, bpd, treatment, years, psychiatrist, therapy
    99: "Cooking",  # bit, rice, big, spray, minutes, outside, add, high, stirring
    100: "Personality Types",  # mbti, sensors, intuitives, types, general, reliability
    101: "TypeScript Interfaces",  # string, interface, typescript, tabledata, id
    102: "Refrigeration Technology",  # fridges, isobutane, cfcs, use, ozone, refrigerants
    103: "Forum Searching",  # search, old, bowl, forum, baking, post, forums, muffins
    104: "Motor Control",  # mosfets, mos2, motor, mos1, channel, 4x, l293d
    105: "Progressive Web Apps",  # html, app, meta, content, service worker, div, web
    106: "Quality Assurance",  # test, testing, grade, priority, validation, click, data
    107: "AI Interaction",  # ai, want, talking ai, talk, starting feel, mindnumbing
    108: "Transportation Planning",  # 10, number, train, billion, eurot, vilnius, station
    109: "Visual Design",  # color, sun, dot, gradient, script, skybox, thumbnail
    110: "Hardware Protocols",  # 00, hidpp, ratbag, raw, read, protocol communication
    111: "System Partitioning",  # bootloader, partition, size, partition type, raw
    112: "Python Development",  # file, line, py, usr, f2py, numpy, python3
    113: "Defense Technology",  # cost, drones, 000, 500, defense, costs, cheap, legal
    114: "3D Printing Software",  # cura, scripts, plugins, postprocessingplugin, share
    115: "City Building Games",  # building, isometric, chill, builder, build, minecraft
    116: "Desktop Widgets",  # calendar, widget, notion, plasma, existing, data, qml
    117: "Public Transit APIs",  # bus, api, digitransit, map, data, tartu, route, time
    118: "Memory Management",  # pointers, memory, pointer, use, rust, ptr, level
    119: "Constructed Languages",  # lojban, lo, mi, nu, like, app, formal, lojbanana
    120: "Hardware Identification",  # mac, component, model, specific, repair, physical
    121: "Process Management",  # 58887, process, powershell, system monitoring
    122: "Educational Content",  # education, learning, teaching, course, tutorial
    123: "Media Processing",  # video, audio, media, processing, encoding, formats
    124: "Cloud Services"  # cloud, services, deployment, infrastructure, scaling
}

def insert_cluster_names():
    """Insert manually created cluster names into the database"""
    
    # Connect to database
    conn = sqlite3.connect('mycelica.db')
    cursor = conn.cursor()
    
    # Create table if it doesn't exist
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cluster_names (
            cluster_id INTEGER PRIMARY KEY,
            level TEXT NOT NULL,
            name TEXT NOT NULL,
            keywords TEXT,
            created_at TEXT NOT NULL,
            is_manual INTEGER DEFAULT 1
        )
    ''')
    
    # Clear existing entries
    cursor.execute('DELETE FROM cluster_names WHERE level = "galaxy"')
    
    # Insert manual cluster names
    current_time = datetime.utcnow().isoformat()
    
    for cluster_id, name in CLUSTER_NAMES.items():
        cursor.execute('''
            INSERT INTO cluster_names (cluster_id, level, name, keywords, created_at, is_manual)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (cluster_id, 'galaxy', name, '[]', current_time, 1))
    
    conn.commit()
    conn.close()
    
    print(f"✅ Inserted {len(CLUSTER_NAMES)} manual cluster names into database")

if __name__ == '__main__':
    insert_cluster_names()