import emojiData from 'unicode-emoji-json/data-by-group.json'
import emojilib from 'emojilib'

interface EmojiEntry {
  emoji: string
  name: string
  slug: string
  skin_tone_support: boolean
  unicode_version: string
  emoji_version: string
}

interface EmojiGroup {
  name: string
  slug: string
  emojis: EmojiEntry[]
}

// Build a searchable index from keywords to emojis
// This creates a mapping like: "laptop" -> "💻", "snake" -> "🐍", etc.
const emojiIndex: Map<string, string> = new Map()

// Process emojilib - this has the most extensive keyword mappings
// Format: { "😀": ["grinning_face", "happy", "smile", ...], ... }
Object.entries(emojilib).forEach(([emoji, keywords]) => {
  if (Array.isArray(keywords)) {
    keywords.forEach(keyword => {
      const key = keyword.toLowerCase().replace(/_/g, ' ')
      if (!emojiIndex.has(key)) {
        emojiIndex.set(key, emoji)
      }
      // Also add without underscores as single word
      const singleWord = keyword.toLowerCase().replace(/_/g, '')
      if (!emojiIndex.has(singleWord) && singleWord.length > 2) {
        emojiIndex.set(singleWord, emoji)
      }
    })
  }
})

// Process unicode-emoji-json for additional coverage
;(emojiData as EmojiGroup[]).forEach(group => {
  group.emojis.forEach(entry => {
    // Add the full name
    const name = entry.name.toLowerCase()
    if (!emojiIndex.has(name)) {
      emojiIndex.set(name, entry.emoji)
    }

    // Also add individual words from the name
    const words = name.split(/[\s\-_]+/)
    words.forEach(word => {
      if (word.length > 2 && !emojiIndex.has(word)) {
        emojiIndex.set(word, entry.emoji)
      }
    })
  })
})

console.log(`Emoji index built with ${emojiIndex.size} keyword mappings`)

// Custom keyword mappings for tech/programming topics (override generic matches)
const customMappings: Record<string, string> = {
  // Programming Languages & Frameworks
  'python': '🐍',
  'javascript': '📜',
  'typescript': '📘',
  'react': '⚛️',
  'vue': '💚',
  'angular': '🅰️',
  'node': '💚',
  'nodejs': '💚',
  'java': '☕',
  'kotlin': '🎯',
  'swift': '🦅',
  'rust': '🦀',
  'go': '🐹',
  'golang': '🐹',
  'ruby': '💎',
  'php': '🐘',
  'csharp': '🎵',
  'c#': '🎵',
  'cpp': '⚙️',
  'c++': '⚙️',

  // Tech & Development
  'code': '💻',
  'coding': '💻',
  'programming': '💻',
  'software': '💻',
  'developer': '👨‍💻',
  'api': '🔌',
  'rest': '🔌',
  'graphql': '◼️',
  'database': '🗄️',
  'sql': '🗄️',
  'nosql': '🗄️',
  'mongodb': '🍃',
  'postgres': '🐘',
  'mysql': '🐬',
  'redis': '🔴',
  'server': '🖥️',
  'backend': '⚙️',
  'frontend': '🎨',
  'fullstack': '🥞',
  'devops': '🔄',
  'docker': '🐳',
  'kubernetes': '☸️',
  'k8s': '☸️',
  'aws': '☁️',
  'azure': '☁️',
  'gcp': '☁️',
  'cloud': '☁️',
  'linux': '🐧',
  'ubuntu': '🐧',
  'windows': '🪟',
  'macos': '🍎',
  'terminal': '💻',
  'bash': '💻',
  'shell': '🐚',
  'git': '📝',
  'github': '🐙',
  'gitlab': '🦊',
  'version': '📝',
  'deploy': '🚀',
  'deployment': '🚀',
  'cicd': '🔄',
  'pipeline': '🔄',
  'test': '🧪',
  'testing': '🧪',
  'unittest': '🧪',
  'debug': '🐛',
  'debugging': '🐛',
  'bug': '🐛',
  'error': '❌',
  'exception': '⚠️',
  'fix': '🔧',
  'refactor': '♻️',
  'optimize': '⚡',
  'performance': '⚡',
  'security': '🔒',
  'auth': '🔐',
  'authentication': '🔐',
  'authorization': '🔐',
  'encryption': '🔐',
  'password': '🔑',
  'token': '🎟️',
  'jwt': '🎟️',
  'oauth': '🔐',

  // AI & Machine Learning
  'ai': '🤖',
  'artificial': '🤖',
  'intelligence': '🤖',
  'machine': '🤖',
  'ml': '🧠',
  'deep': '🧠',
  'learning': '🧠',
  'neural': '🧠',
  'network': '🕸️',
  'model': '🎯',
  'training': '🏋️',
  'dataset': '📊',
  'tensor': '🔢',
  'pytorch': '🔥',
  'tensorflow': '🔶',
  'gpt': '🤖',
  'chatgpt': '🤖',
  'claude': '🧠',
  'llm': '🤖',
  'nlp': '💬',
  'prompt': '💬',
  'embedding': '📍',
  'vector': '📍',
  'rag': '📚',
  'agent': '🤖',
  'langchain': '🔗',
  'openai': '🤖',
  'anthropic': '🧠',
  'huggingface': '🤗',

  // Data & Analytics
  'data': '📊',
  'analytics': '📈',
  'visualization': '📊',
  'chart': '📈',
  'graph': '📊',
  'dashboard': '📊',
  'report': '📋',
  'metric': '📏',
  'kpi': '📏',
  'statistics': '📉',
  'pandas': '🐼',
  'numpy': '🔢',
  'jupyter': '📓',
  'notebook': '📓',

  // Web & Internet
  'web': '🌐',
  'website': '🌐',
  'http': '🌐',
  'https': '🔒',
  'url': '🔗',
  'link': '🔗',
  'browser': '🌐',
  'chrome': '🌐',
  'firefox': '🦊',
  'safari': '🧭',
  'html': '📄',
  'css': '🎨',
  'sass': '🎨',
  'tailwind': '🌊',
  'bootstrap': '🅱️',
  'responsive': '📱',
  'mobile': '📱',
  'app': '📱',
  'ios': '🍎',
  'android': '🤖',

  // Writing & Content
  'write': '✍️',
  'writing': '✍️',
  'blog': '📝',
  'article': '📰',
  'post': '📝',
  'content': '📝',
  'copy': '📝',
  'copywriting': '✍️',
  'story': '📖',
  'book': '📚',
  'novel': '📖',
  'fiction': '📖',
  'essay': '📄',
  'poem': '🎭',
  'poetry': '🎭',
  'script': '🎬',
  'screenplay': '🎬',
  'documentation': '📚',
  'docs': '📚',
  'readme': '📖',
  'tutorial': '👨‍🏫',
  'guide': '📖',
  'manual': '📖',

  // Business & Work
  'business': '💼',
  'startup': '🚀',
  'entrepreneur': '💼',
  'company': '🏢',
  'corporate': '🏢',
  'office': '🏢',
  'work': '👔',
  'job': '💼',
  'career': '📈',
  'resume': '📄',
  'cv': '📄',
  'interview': '🎤',
  'hiring': '🤝',
  'meeting': '🤝',
  'presentation': '📊',
  'slide': '📊',
  'pitch': '🎯',
  'strategy': '♟️',
  'plan': '📅',
  'planning': '📅',
  'project': '📋',
  'task': '✅',
  'todo': '✅',
  'deadline': '⏰',
  'schedule': '📅',
  'calendar': '📅',
  'email': '📧',
  'mail': '📧',
  'message': '💬',
  'communication': '💬',
  'slack': '💬',
  'teams': '💬',
  'zoom': '📹',
  'video': '📹',
  'call': '📞',
  'conference': '🎤',

  // Finance & Money
  'money': '💰',
  'finance': '💵',
  'financial': '💵',
  'investment': '📈',
  'invest': '📈',
  'stock': '📈',
  'crypto': '₿',
  'bitcoin': '₿',
  'ethereum': '⟠',
  'blockchain': '🔗',
  'bank': '🏦',
  'banking': '🏦',
  'payment': '💳',
  'transaction': '💳',
  'budget': '💰',
  'tax': '🧾',
  'accounting': '🧮',
  'revenue': '💵',
  'profit': '💵',
  'sales': '💵',
  'pricing': '🏷️',

  // Science & Research
  'science': '🔬',
  'scientific': '🔬',
  'research': '🔍',
  'study': '📖',
  'experiment': '🧫',
  'hypothesis': '💡',
  'theory': '📐',
  'physics': '⚛️',
  'chemistry': '🧪',
  'biology': '🧬',
  'genetics': '🧬',
  'dna': '🧬',
  'medicine': '💊',
  'medical': '🏥',
  'health': '❤️',
  'healthcare': '🏥',
  'doctor': '👨‍⚕️',
  'patient': '🏥',
  'math': '🔢',
  'mathematics': '🔢',
  'calculus': '📐',
  'algebra': '🔢',
  'geometry': '📐',
  'equation': '🔢',
  'formula': '🔢',
  'algorithm': '📐',

  // Education
  'education': '🎓',
  'school': '🏫',
  'university': '🎓',
  'college': '🎓',
  'student': '👨‍🎓',
  'teacher': '👨‍🏫',
  'professor': '👨‍🏫',
  'course': '🎓',
  'class': '🎓',
  'lesson': '📖',
  'homework': '📝',
  'assignment': '📝',
  'exam': '📝',
  'quiz': '❓',
  'learn': '📚',
  'teach': '👨‍🏫',
  'explain': '💡',
  'understand': '🤔',
  'question': '❓',
  'answer': '✅',
  'help': '🆘',

  // Design & Creative
  'design': '🎨',
  'designer': '🎨',
  'ui': '🖼️',
  'ux': '👤',
  'interface': '🖼️',
  'wireframe': '📐',
  'mockup': '🖼️',
  'prototype': '🔧',
  'figma': '🎨',
  'sketch': '✏️',
  'photoshop': '🎨',
  'illustrator': '🎨',
  'graphic': '🎨',
  'logo': '🏷️',
  'brand': '🏷️',
  'branding': '🏷️',
  'color': '🌈',
  'font': '🔤',
  'typography': '🔤',
  'layout': '📐',
  'animation': '🎬',
  'motion': '🎬',
  '3d': '🎲',
  'render': '🖼️',

  // Media & Entertainment
  'music': '🎵',
  'song': '🎵',
  'audio': '🔊',
  'sound': '🔊',
  'podcast': '🎙️',
  'radio': '📻',
  'movie': '🎬',
  'film': '🎬',
  'cinema': '🎬',
  'tv': '📺',
  'television': '📺',
  'show': '📺',
  'series': '📺',
  'netflix': '📺',
  'youtube': '▶️',
  'stream': '📺',
  'streaming': '📺',
  'game': '🎮',
  'gaming': '🎮',
  'gamer': '🎮',
  'esports': '🎮',
  'player': '🎮',
  'art': '🎨',
  'artist': '🎨',
  'paint': '🎨',
  'draw': '✏️',
  'drawing': '✏️',
  'photo': '📷',
  'photography': '📷',
  'camera': '📷',
  'image': '🖼️',
  'picture': '🖼️',

  // Communication & Language
  'language': '🗣️',
  'translate': '🌍',
  'translation': '🌍',
  'english': '🇬🇧',
  'spanish': '🇪🇸',
  'french': '🇫🇷',
  'german': '🇩🇪',
  'chinese': '🇨🇳',
  'japanese': '🇯🇵',
  'korean': '🇰🇷',
  'portuguese': '🇧🇷',
  'italian': '🇮🇹',
  'russian': '🇷🇺',
  'arabic': '🇸🇦',
  'hindi': '🇮🇳',
  'grammar': '📝',
  'vocabulary': '📚',
  'speak': '🗣️',
  'speech': '🗣️',
  'voice': '🗣️',
  'conversation': '💬',
  'chat': '💭',
  'discuss': '💬',
  'debate': '💬',

  // Life & Personal
  'life': '🌱',
  'lifestyle': '🌱',
  'personal': '👤',
  'self': '👤',
  'growth': '🌱',
  'improve': '📈',
  'habit': '🔄',
  'routine': '🔄',
  'morning': '🌅',
  'evening': '🌆',
  'night': '🌙',
  'sleep': '😴',
  'dream': '💭',
  'goal': '🎯',
  'motivation': '💪',
  'inspire': '✨',
  'success': '🏆',
  'achieve': '🏆',
  'failure': '📉',
  'mindset': '🧠',
  'mental': '🧠',
  'psychology': '🧠',
  'emotion': '❤️',
  'feeling': '❤️',
  'happy': '😊',
  'sad': '😢',
  'stress': '😰',
  'anxiety': '😰',
  'relax': '😌',
  'meditation': '🧘',
  'mindfulness': '🧘',
  'yoga': '🧘',
  'fitness': '💪',
  'exercise': '🏃',
  'workout': '💪',
  'gym': '🏋️',
  'sport': '⚽',
  'run': '🏃',
  'running': '🏃',
  'walk': '🚶',
  'hiking': '🥾',
  'outdoor': '🏕️',
  'nature': '🌿',
  'environment': '🌍',
  'climate': '🌡️',
  'weather': '⛅',

  // Food & Cooking
  'food': '🍽️',
  'eat': '🍽️',
  'cook': '👨‍🍳',
  'cooking': '👨‍🍳',
  'recipe': '👨‍🍳',
  'meal': '🍽️',
  'breakfast': '🍳',
  'lunch': '🥪',
  'dinner': '🍽️',
  'restaurant': '🍽️',
  'kitchen': '👨‍🍳',
  'ingredient': '🥬',
  'nutrition': '🥗',
  'diet': '🥗',
  'vegetarian': '🥬',
  'vegan': '🥬',
  'coffee': '☕',
  'tea': '🍵',
  'drink': '🥤',
  'wine': '🍷',
  'beer': '🍺',

  // Travel & Places
  'travel': '✈️',
  'trip': '🧳',
  'vacation': '🏖️',
  'holiday': '🎄',
  'flight': '✈️',
  'airport': '✈️',
  'hotel': '🏨',
  'booking': '📅',
  'destination': '📍',
  'country': '🌍',
  'city': '🏙️',
  'map': '🗺️',
  'location': '📍',
  'adventure': '🏔️',
  'explore': '🔍',
  'tour': '🧳',
  'tourist': '📷',
  'beach': '🏖️',
  'mountain': '🏔️',
  'forest': '🌲',
  'ocean': '🌊',
  'island': '🏝️',

  // Home & Family
  'home': '🏠',
  'house': '🏠',
  'apartment': '🏢',
  'room': '🚪',
  'furniture': '🪑',
  'decor': '🖼️',
  'garden': '🌻',
  'family': '👨‍👩‍👧‍👦',
  'parent': '👨‍👩‍👧',
  'child': '👶',
  'baby': '👶',
  'kid': '🧒',
  'pet': '🐾',
  'dog': '🐕',
  'cat': '🐱',
  'relationship': '❤️',
  'love': '❤️',
  'friend': '🤝',
  'friendship': '🤝',
  'social': '👥',

  // Shopping & E-commerce
  'shop': '🛒',
  'shopping': '🛒',
  'buy': '🛒',
  'sell': '💵',
  'store': '🏪',
  'ecommerce': '🛒',
  'product': '📦',
  'order': '📦',
  'delivery': '🚚',
  'shipping': '🚚',
  'cart': '🛒',
  'checkout': '💳',
  'discount': '🏷️',
  'sale': '🏷️',
  'deal': '🤝',
  'offer': '🎁',
  'coupon': '🎟️',
  'customer': '👤',
  'review': '⭐',
  'rating': '⭐',

  // Legal & Contracts
  'legal': '⚖️',
  'law': '⚖️',
  'lawyer': '⚖️',
  'attorney': '⚖️',
  'contract': '📜',
  'agreement': '🤝',
  'terms': '📜',
  'policy': '📜',
  'privacy': '🔒',
  'copyright': '©️',
  'trademark': '™️',
  'patent': '📜',
  'license': '📜',
  'compliance': '✅',
  'regulation': '📜',

  // Misc & General
  'idea': '💡',
  'concept': '💡',
  'think': '🤔',
  'thinking': '🤔',
  'brainstorm': '🧠',
  'problem': '🔧',
  'solution': '✨',
  'solve': '✨',
  'create': '✨',
  'build': '🏗️',
  'make': '🛠️',
  'develop': '🔧',
  'generate': '⚡',
  'automate': '🤖',
  'automation': '🤖',
  'workflow': '🔄',
  'process': '⚙️',
  'system': '⚙️',
  'tool': '🔧',
  'utility': '🔧',
  'feature': '✨',
  'update': '🔄',
  'upgrade': '⬆️',
  'version': '📝',
  'release': '🚀',
  'launch': '🚀',
  'announce': '📢',
  'news': '📰',
  'trend': '📈',
  'popular': '🔥',
  'viral': '🔥',
  'share': '🔗',
  'save': '💾',
  'download': '⬇️',
  'upload': '⬆️',
  'file': '📄',
  'folder': '📁',
  'document': '📄',
  'pdf': '📄',
  'excel': '📊',
  'word': '📝',
  'spreadsheet': '📊',
  'template': '📋',
  'example': '📌',
  'sample': '📌',
  'demo': '🎯',
  'preview': '👁️',
  'draft': '📝',
  'edit': '✏️',
  'delete': '🗑️',
  'remove': '🗑️',
  'add': '➕',
  'new': '🆕',
  'old': '📜',
  'archive': '📦',
  'backup': '💾',
  'restore': '🔄',
  'sync': '🔄',
  'connect': '🔗',
  'disconnect': '🔌',
  'online': '🌐',
  'offline': '📴',
  'wifi': '📶',
  'internet': '🌐',
  'network': '🕸️',
  'setting': '⚙️',
  'config': '⚙️',
  'configuration': '⚙️',
  'option': '☑️',
  'preference': '⚙️',
  'customize': '🎨',
  'theme': '🎨',
  'dark': '🌙',
  'light': '☀️',
  'mode': '🔄',
  'toggle': '🔄',
  'switch': '🔄',
  'enable': '✅',
  'disable': '❌',
  'on': '✅',
  'off': '❌',
  'start': '▶️',
  'stop': '⏹️',
  'pause': '⏸️',
  'play': '▶️',
  'next': '⏭️',
  'previous': '⏮️',
  'forward': '⏩',
  'backward': '⏪',
  'fast': '⚡',
  'slow': '🐢',
  'quick': '⚡',
  'instant': '⚡',
  'wait': '⏳',
  'loading': '⏳',
  'progress': '📊',
  'complete': '✅',
  'done': '✅',
  'finish': '🏁',
  'success': '✅',
  'fail': '❌',
  'warning': '⚠️',
  'info': 'ℹ️',
  'tip': '💡',
  'note': '📝',
  'important': '❗',
  'urgent': '🚨',
  'priority': '🔝',
  'favorite': '⭐',
  'bookmark': '🔖',
  'pin': '📌',
  'tag': '🏷️',
  'label': '🏷️',
  'category': '📂',
  'group': '👥',
  'list': '📋',
  'table': '📊',
  'sort': '🔄',
  'filter': '🔍',
  'search': '🔍',
  'find': '🔍',
  'lookup': '🔍',
  'query': '🔍',
  'result': '📋',
  'output': '📤',
  'input': '📥',
  'form': '📝',
  'field': '📝',
  'button': '🔘',
  'click': '👆',
  'tap': '👆',
  'scroll': '📜',
  'drag': '✋',
  'drop': '📥',
  'copy': '📋',
  'paste': '📋',
  'cut': '✂️',
  'undo': '↩️',
  'redo': '↪️',
  'reset': '🔄',
  'clear': '🗑️',
  'empty': '📭',
  'full': '📬',
  'open': '📂',
  'close': '📁',
  'expand': '🔽',
  'collapse': '🔼',
  'show': '👁️',
  'hide': '🙈',
  'visible': '👁️',
  'hidden': '🙈',
  'public': '🌐',
  'private': '🔒',
  'secure': '🔒',
  'safe': '✅',
  'danger': '⚠️',
  'risk': '⚠️',
  'issue': '❗',
  'ticket': '🎫',
  'support': '🆘',
  'feedback': '💬',
  'comment': '💬',
  'reply': '↩️',
  'mention': '@',
  'notify': '🔔',
  'notification': '🔔',
  'alert': '🚨',
  'remind': '⏰',
  'reminder': '⏰',
  'event': '📅',
  'date': '📅',
  'time': '⏰',
  'today': '📅',
  'tomorrow': '📅',
  'yesterday': '📅',
  'week': '📅',
  'month': '📅',
  'year': '📅',
  'daily': '📅',
  'weekly': '📅',
  'monthly': '📅',
  'annual': '📅',
  'birthday': '🎂',
  'anniversary': '🎉',
  'celebrate': '🎉',
  'party': '🎉',
  'gift': '🎁',
  'present': '🎁',
  'surprise': '🎉',
  'congratulations': '🎊',
  'congrats': '🎊',
  'welcome': '👋',
  'goodbye': '👋',
  'hello': '👋',
  'hi': '👋',
  'thanks': '🙏',
  'thank': '🙏',
  'please': '🙏',
  'sorry': '😔',
  'excuse': '🙏',
  'wow': '😮',
  'amazing': '🤩',
  'awesome': '🔥',
  'great': '👍',
  'good': '👍',
  'bad': '👎',
  'best': '🏆',
  'worst': '👎',
  'top': '🔝',
  'bottom': '🔽',
  'first': '1️⃣',
  'second': '2️⃣',
  'third': '3️⃣',
  'last': '🔚',
  'final': '🏁',
  'beginning': '🚀',
  'end': '🏁',
  'middle': '🔘',
  'center': '🎯',
  'left': '⬅️',
  'right': '➡️',
  'up': '⬆️',
  'down': '⬇️',
  'forward': '➡️',
  'back': '⬅️',
  'here': '📍',
  'there': '👉',
  'where': '❓',
  'when': '⏰',
  'what': '❓',
  'why': '❓',
  'how': '❓',
  'who': '👤',
  'which': '🤔',
  'all': '🌐',
  'none': '⭕',
  'some': '🔘',
  'many': '📊',
  'few': '🔘',
  'more': '➕',
  'less': '➖',
  'most': '📈',
  'least': '📉',
  'big': '🔺',
  'small': '🔻',
  'large': '🔺',
  'tiny': '🔻',
  'long': '📏',
  'short': '📐',
  'high': '⬆️',
  'low': '⬇️',
  'hot': '🔥',
  'cold': '❄️',
  'warm': '🌡️',
  'cool': '😎',
  'free': '🆓',
  'paid': '💵',
  'premium': '💎',
  'basic': '📋',
  'advanced': '🚀',
  'pro': '⭐',
  'enterprise': '🏢',
  'team': '👥',
  'solo': '👤',
  'single': '1️⃣',
  'multiple': '🔢',
  'double': '2️⃣',
  'triple': '3️⃣',
  'zero': '0️⃣',
  'hundred': '💯',
  'thousand': '🔢',
  'million': '🔢',
  'billion': '🔢',
  'percent': '%',
  'percentage': '📊',
  'ratio': '📊',
  'rate': '📊',
  'score': '🏆',
  'point': '📍',
  'level': '📊',
  'rank': '🏆',
  'tier': '📊',
  'stage': '🎭',
  'phase': '🔄',
  'step': '👣',
  'action': '⚡',
  'activity': '📊',
  'status': '📊',
  'state': '📊',
  'condition': '📊',
  'situation': '📊',
  'context': '📋',
  'background': '🖼️',
  'history': '📜',
  'future': '🔮',
  'present': '📍',
  'past': '📜',
  'now': '⏰',
  'later': '⏰',
  'soon': '⏰',
  'never': '❌',
  'always': '♾️',
  'sometimes': '🔄',
  'often': '🔄',
  'rarely': '🔘',
  'maybe': '🤔',
  'probably': '🤔',
  'definitely': '✅',
  'certainly': '✅',
  'possibly': '🤔',
  'likely': '📈',
  'unlikely': '📉',
  'random': '🎲',
  'specific': '🎯',
  'general': '🌐',
  'particular': '📌',
  'unique': '✨',
  'common': '📋',
  'rare': '💎',
  'special': '⭐',
  'normal': '📋',
  'standard': '📋',
  'custom': '🎨',
  'default': '📋',
  'original': '📜',
  'modified': '✏️',
  'changed': '🔄',
  'updated': '🔄',
  'revised': '✏️',
  'improved': '📈',
  'enhanced': '✨',
  'fixed': '🔧',
  'broken': '💔',
  'working': '✅',
  'failed': '❌',
  'pending': '⏳',
  'approved': '✅',
  'rejected': '❌',
  'cancelled': '❌',
  'confirmed': '✅',
  'verified': '✅',
  'valid': '✅',
  'invalid': '❌',
  'correct': '✅',
  'incorrect': '❌',
  'right': '✅',
  'wrong': '❌',
  'true': '✅',
  'false': '❌',
  'yes': '✅',
  'no': '❌',
  'ok': '👌',
  'okay': '👌',
  'agree': '✅',
  'disagree': '❌',
  'accept': '✅',
  'decline': '❌',
  'allow': '✅',
  'deny': '❌',
  'permit': '✅',
  'forbid': '🚫',
  'block': '🚫',
  'unblock': '✅',
  'ban': '🚫',
  'mute': '🔇',
  'unmute': '🔊',
  'lock': '🔒',
  'unlock': '🔓',
}

// Add custom mappings to the index (these take priority)
Object.entries(customMappings).forEach(([keyword, emoji]) => {
  emojiIndex.set(keyword.toLowerCase(), emoji)
})

/**
 * Get the best matching emoji for a node based on its title and keywords
 */
export function getEmojiForNode(node: {
  title?: string
  label?: string
  keywords?: string[]
}): string {
  const keywordsText = node.keywords ? node.keywords.join(' ') : ''
  const titleText = node.title || node.label || ''
  const searchText = (titleText + ' ' + keywordsText).toLowerCase()

  // Split into words and try to find matches
  const words = searchText.split(/[\s\-_,.:;!?'"()\[\]{}]+/).filter(w => w.length > 2)

  // Try exact word matches first (custom mappings have priority)
  for (const word of words) {
    if (customMappings[word]) {
      return customMappings[word]
    }
  }

  // Then try the full emoji index
  for (const word of words) {
    const emoji = emojiIndex.get(word)
    if (emoji) {
      return emoji
    }
  }

  // Try partial matches (word contains keyword or keyword contains word)
  for (const word of words) {
    for (const [keyword, emoji] of Object.entries(customMappings)) {
      if (word.includes(keyword) || keyword.includes(word)) {
        return emoji
      }
    }
  }

  // Default emoji
  return '💭'
}

/**
 * Get all available emoji categories for reference
 */
export function getEmojiCategories(): string[] {
  return (emojiData as EmojiGroup[]).map(group => group.name)
}

/**
 * Search for emojis by keyword
 */
export function searchEmojis(query: string, limit = 10): Array<{ emoji: string, name: string }> {
  const results: Array<{ emoji: string, name: string }> = []
  const queryLower = query.toLowerCase()

  for (const group of emojiData as EmojiGroup[]) {
    for (const entry of group.emojis) {
      if (entry.name.toLowerCase().includes(queryLower)) {
        results.push({ emoji: entry.emoji, name: entry.name })
        if (results.length >= limit) return results
      }
    }
  }

  return results
}
